apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  replicas: 3

  selector:
    matchLabels:
      app: nginx-app

  template:
    metadata:
      labels:
        app: nginx-app

    spec:
      containers:
        - name: nginx
          image: nginx:alpine

          volumeMounts:
            - name: nginx-index-html
              mountPath: /usr/share/nginx/html/

      volumes:
        - name: nginx-index-html
          configMap:
            name: nginx-index-html
            items:
              - key: index.html
                path: index.html
