FROM golang:alpine

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -a -installsuffix cgo -o main .

FROM scratch

COPY --from=0 /go/main .

COPY --from=0 /go/templates/ ./templates

EXPOSE 8000

CMD [ "./main" ]

# REPOSITORY                    TAG                   IMAGE ID            CREATED             SIZE
# zenatureza/go-server          latest                fcefd1d07e82        13 seconds ago       7.2MB
